name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: <desired_version>  # Replace <desired_version> with the Terraform version you want to use
        
    - name: Initialize Terraform
      run: terraform init
      
    - name: Plan Terraform Changes
      run: terraform plan
      
    - name: Apply Terraform Changes
      run: terraform apply -auto-approve
      env:
        TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Add other Terraform variables as needed
        
    - name: Terraform Clean-Up
      run: terraform destroy -auto-approve
      if: always()  # Always run the destroy step, even if previous steps fail

